[package]
name = "st"
version = "0.1.0"
edition = "2021"

[dependencies]
gears = { path = "../../gears" }
store = { path = "../../store" }
database = { path = "../../database" }
proto-types = { path = "../../proto-types" }
proto-messages = { path = "../../proto-messages" }
ibc-proto = { workspace = true }

# bytes = "1.2.1"
# serde = { version = "1.0", default-features = false }
# #params-module = { package = "params", path = "../params" }
# cosmwasm-std = "1.1.5"
# tendermint-informal = { package = "tendermint", git = "https://github.com/joneskm/tendermint-rs" }
# auth = { path = "../auth" }
# tendermint-proto = { git = "https://github.com/joneskm/tendermint-rs" }
# anyhow = "1.0.70"
# clap = { version = "4.2.2", features = ["derive"] }
# tendermint-rpc = { git = "https://github.com/joneskm/tendermint-rs", features = [
#     "http-client",
# ] }
# tokio = "1.27.0"
# serde_json = "1.0.93"
# ibc-relayer = "0.23.0"
# prost = { version = "0.11" }
# strum = "0.24.1"
# strum_macros = "0.24"
# axum = "0.6.18"
# tendermint-abci = { git = "https://github.com/joneskm/tendermint-rs" }
#
# [dev-dependencies]
# hex = "0.4.3"
